site_name: Dokumentace a návody
site_url: https://jirihusak.github.io/majordomus/
site_description: Open-source smart home system

theme:
  name: material
  logo: assets/logoWhite.png
  favicon: assets/favicon.png
  language: cs
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Tmavý režim
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Světlý režim
  features:
    #- navigation.sections
    #- navigation.expand
    - search.suggest
    #- navigation.indexes
    - navigation.top
    - toc.integrate
    - search.highlight
    - content.code.copy

nav:
  - Začínáme: 
    - Úvod: cs/index.md
    - Proč Majordomus: cs/why-majordomus.md
    - Cenové srovnání: cs/price-comparison.md
  - Hardware:
    - Co potřebuji pro start: cs/how-start.md
    - Topologie: cs/topology.md
    - RoomSensor: cs/hw-roomsensor.md
    - RoomIO: cs/hw-roomio.md
    - BoxIO: cs/hw-boxio.md
    - Převodník RS485 2 USB: cs/hw-rs485-usb.md
  - Home Assistant:
    - Co je Home Assistant: cs/ha-introduction.md
    - Instalace: cs/ha-installation.md
    - Konfigurace Home Assistant: cs/ha-configuration.md
  - Majordomus Control:
    - Architektura SW: cs/sw-architecture.md
    - Instalace SW: cs/sw-installation.md
    - Konfigurace SW: cs/sw-configuration.md
    - Aktualizace firmware: cs/fw-update.md
  - Node-RED:
    - Co je Node-RED: cs/sw-node-red.md
  - Pro vývojáře:
    - MQTT protokol: cs/dev-mqtt-protocol.md
    - Protokol RS-485: cs/dev-rs485-protocol.md
  - Řešení problémů: cs/troubleshooting.md
    

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  alternate:
    - name: Česky
      link: /majordomus/cs/
      lang: cs
    - name: English
      link: /majordomus/en/
      lang: en

extra_css:
  - stylesheets/extra.css

